#!/bin/bash
matrix1=(1 2 3 4 5 6 7 8 9)
matrix2=(11 12 13 14 15 16 17 18 19)

echo "Addition of two matrices:"

for (( i=0; i<9; i++ ))
do
  # 1. Add the matching elements
  sum=$(( ${matrix1[i]} + ${matrix2[i]} ))
  
  # 2. Print the sum on the same line
  echo -n "$sum "

  # 3. Create the 3x3 grid by breaking the line every 3 numbers
  if [ $(( (i+1) % 3 )) -eq 0 ]
  then
    echo ""
  fi
done
